apiVersion: constraints.gatekeeper.sh/v1beta1
kind: FluxMultiTenancy
metadata:
  name: flux-multi-tenancy
spec:
  match:
    kinds:
      - apiGroups: ["helm.toolkit.fluxcd.io"]
        kinds: ["HelmRelease"]
      - apiGroups: ["kustomize.toolkit.fluxcd.io"]
        kinds: ["Kustomization"]
    excludedNamespaces:
      - "flux-system"